### ISSUE TITLE
pg_curl.c:33:26: error: missing binary operator before token "("

### ISSUE THREAD

**Issue by flight228** [RekGRpth/pg_curl#10]
Привет!
Пытаюсь смэйкать и вот, что получается:
[root@1657427-cj46392 extension]# make
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pg_curl.o pg_curl.c
pg_curl.c:33:26: error: missing binary operator before token "("
 #if CURL_AT_LEAST_VERSION(7, 56, 0)
                          ^
pg_curl.c:51:26: error: missing binary operator before token "("
 #if CURL_AT_LEAST_VERSION(7, 20, 0)
                          ^
pg_curl.c:74:1: warning: missing braces around initializer [-Wmissing-braces]
 static pg_curl_t pg_curl = {0};
 ^
pg_curl.c:74:1: warning: (near initialization for ‘pg_curl.conname’) [-Wmissing-braces]
pg_curl.c:93:26: error: missing binary operator before token "("
 #if CURL_AT_LEAST_VERSION(7, 12, 0)
                          ^

и так далее. 
Что я делаю не так?
CentOS7 , gcc-4.8.5-44.el7.x86_64

**Comment by RekGRpth** [comment]
Попробуйте компилятор по-новее, например, так
```sh
yum install -y centos-release-scl epel-release
yum install -y devtoolset-11-toolchain
source scl_source enable devtoolset-11
```

**Comment by flight228** [comment]
Получилось, теперь другая проблема:
postgres@postgres=# CREATE EXTENSION pg_curl;
ERROR:  could not load library "/usr/pgsql-14/lib/pg_curl.so": /usr/pgsql-14/lib/pg_curl.so: undefined symbol: curl_multi_poll

Файл pg_curl.so в /usr/pgsql-14/lib скопирован
ОСь: Oracle  Linux 8.8 (ака Fedora)

**Comment by RekGRpth** [comment]
Поправил

**Comment by flight228** [comment]
Благодарю, взлетело.
