### ISSUE TITLE
ftp upload

### ISSUE THREAD

**Issue by Iced-Sun** [RekGRpth/pg_curl#13]
Hi, 

I am new to libcurl and pg_curl. I found the example for ftp uploading on https://curl.se/libcurl/c/ftpupload.html, but failed to make it work with pg_curl because I didn't find how to set the `CURLOPT_READDATA` option.

Am I missing anything?

**Comment by RekGRpth** [comment]
https://github.com/RekGRpth/pg_curl/issues/7 may be help?

**Comment by Iced-Sun** [comment]
If I understand it correctly, #7 added support for `CURLOPT_*QUOTE` to send commands before or after the transfer ([link](https://curl.se/libcurl/c/CURLOPT_QUOTE.html)). What I am looking for is how to set the upload content, which is determined by  the `CURLOPT_READDATA` option, according to the [example](https://curl.se/libcurl/c/ftpupload.html).

**Comment by RekGRpth** [comment]
Try curl_easy_setopt_postfields

**Comment by Iced-Sun** [comment]
> Try curl_easy_setopt_postfields

Yep, tried `curl_easy_setopt_postfields`, `curl_postfield_append` and `curl_mime_data` with no luck.

For reference, here are some test cases.

1. 
```sql
WITH s AS (SELECT
  curl_easy_reset(),
  curl_easy_setopt_upload(1),
  curl_easy_setopt_url('ftp://ftp.com/dir/test.txt'),
  curl_easy_perform(),
  curl_easy_getinfo_data_in()
)
select curl_easy_getinfo_header_in(), curl_easy_getinfo_data_out(), * from s;
```
will upload an empty file `test.txt`.

2. 
```sql
WITH s AS (SELECT
  curl_easy_reset(),
  curl_easy_setopt_upload(1),
  curl_easy_setopt_url('ftp://ftp.com/dir/test.txt'),
  curl_easy_setopt_postfields('content'),
  curl_easy_perform(),
  curl_easy_getinfo_data_in()
)
select curl_easy_getinfo_header_in(), curl_easy_getinfo_data_out(), * from s;
```
will fetch the content and then **remove** the file `test.txt`.

**Comment by RekGRpth** [comment]
I think, you need using curl_quote_append according to example, also curl_easy_setopt_postfields accepts bytea, not text!

**Comment by Iced-Sun** [comment]
> I think, you need using curl_quote_append according to example, also curl_easy_setopt_postfields accepts bytea, not text!

Still the same: nothing is uploaded and the remote file is deleted if the same file exists.
```sql
WITH s AS (SELECT
  curl_easy_reset(),
  curl_easy_setopt_upload(1),
  curl_easy_setopt_url('ftp://ftp.com/dir/test.txt'),
  curl_postquote_append('RNFR test.txt'),
  curl_postquote_append('RNTO test.txt'),
  curl_easy_setopt_postfields('content'::bytea),
  curl_easy_perform(),
  curl_easy_getinfo_data_in()
)
select curl_easy_getinfo_header_in(), curl_easy_getinfo_data_out(), * from s;
```

**Comment by RekGRpth** [comment]
issue was fixed by https://github.com/RekGRpth/pg_curl/commit/b4ff6031d06ef21260924c47ddac19158a1a11e0
thanx for report
I test it so
```sql
create extension if not exists pg_curl;

begin;
select curl_easy_reset();

select curl_easy_setopt_verbose(1);

select curl_easy_setopt_password('rNrKYTX9g7z3RgJRmxWuGHbeu');
select curl_easy_setopt_readdata(convert_to(now()::text, 'utf-8'));
select curl_easy_setopt_url('ftp://ftp.dlptest.com/file.txt');
select curl_easy_setopt_username('dlpuser');

select curl_easy_perform();

select convert_from(curl_easy_getinfo_data_in(), 'utf-8');
select convert_from(curl_easy_getinfo_data_out(), 'utf-8');
select curl_easy_getinfo_debug();
select curl_easy_getinfo_header_in();
select curl_easy_getinfo_header_out();

select curl_easy_getinfo_errcode(), curl_easy_getinfo_errdesc(), curl_easy_getinfo_errbuf();
end;

begin;
select curl_easy_reset();

select curl_easy_setopt_verbose(1);

select curl_easy_setopt_password('rNrKYTX9g7z3RgJRmxWuGHbeu');
select curl_easy_setopt_url('ftp://ftp.dlptest.com/file.txt');
select curl_easy_setopt_username('dlpuser');

select curl_easy_perform();

select convert_from(curl_easy_getinfo_data_in(), 'utf-8');
select convert_from(curl_easy_getinfo_data_out(), 'utf-8');
select curl_easy_getinfo_debug();
select curl_easy_getinfo_header_in();
select curl_easy_getinfo_header_out();

select curl_easy_getinfo_errcode(), curl_easy_getinfo_errdesc(), curl_easy_getinfo_errbuf();
end;
```
