### ISSUE TITLE
Getting build error 

### ISSUE THREAD

**Issue by asharabu** [RekGRpth/pg_curl#3]
Hi,

I am getting a build error on postgresql13.

> 

root@user:/tmp/pg_curl# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_curl.o pg_curl.c
pg_curl.c: In function âpg_curl_easy_setopt_doh_urlâ:
pg_curl.c:315:82: error: âCURLOPT_DOH_URLâ undeclared (first use in this function); did you mean âCURLOPT_URLâ?
 EXTENSION(pg_curl_easy_setopt_doh_url) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_DOH_URL); }
                                                                                  ^~~~~~~~~~~~~~~
                                                                                  CURLOPT_URL
pg_curl.c:315:82: note: each undeclared identifier is reported only once for each function it appears in
pg_curl.c: In function âpg_curl_easy_setopt_proxy_tls13_ciphersâ:
pg_curl.c:344:94: error: âCURLOPT_PROXY_TLS13_CIPHERSâ undeclared (first use in this function); did you mean âCURLOPT_PROXY_SSL_CIPHER_LISTâ?
 EXTENSION(pg_curl_easy_setopt_proxy_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_PROXY_TLS13_CIPHERS); }
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                              CURLOPT_PROXY_SSL_CIPHER_LIST
pg_curl.c: In function âpg_curl_easy_setopt_tls13_ciphersâ:
pg_curl.c:369:88: error: âCURLOPT_TLS13_CIPHERSâ undeclared (first use in this function); did you mean âCURLOPT_DNS_SERVERSâ?
 EXTENSION(pg_curl_easy_setopt_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_TLS13_CIPHERS); }
                                                                                        ^~~~~~~~~~~~~~~~~~~~~
                                                                                        CURLOPT_DNS_SERVERS
pg_curl.c: In function âpg_curl_easy_setopt_disallow_username_in_urlâ:
pg_curl.c:401:99: error: âCURLOPT_DISALLOW_USERNAME_IN_URLâ undeclared (first use in this function); did you mean âCURLOPT_TLSAUTH_USERNAMEâ?
 EXTENSION(pg_curl_easy_setopt_disallow_username_in_url) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DISALLOW_USERNAME_IN_URL); }
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                   CURLOPT_TLSAUTH_USERNAME
pg_curl.c: In function âpg_curl_easy_setopt_dns_shuffle_addressesâ:
pg_curl.c:403:96: error: âCURLOPT_DNS_SHUFFLE_ADDRESSESâ undeclared (first use in this function); did you mean âCURLOPT_DNS_SERVERSâ?
 EXTENSION(pg_curl_easy_setopt_dns_shuffle_addresses) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DNS_SHUFFLE_ADDRESSES); }
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                CURLOPT_DNS_SERVERS
pg_curl.c: In function âpg_curl_easy_setopt_happy_eyeballs_timeout_msâ:
pg_curl.c:420:100: error: âCURLOPT_HAPPY_EYEBALLS_TIMEOUT_MSâ undeclared (first use in this function); did you mean âCURLOPT_EXPECT_100_TIMEOUT_MSâ?
 EXTENSION(pg_curl_easy_setopt_happy_eyeballs_timeout_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS); }
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                    CURLOPT_EXPECT_100_TIMEOUT_MS
pg_curl.c: In function âpg_curl_easy_setopt_haproxyprotocolâ:
pg_curl.c:421:90: error: âCURLOPT_HAPROXYPROTOCOLâ undeclared (first use in this function); did you mean âCURLOPT_DEFAULT_PROTOCOLâ?
 EXTENSION(pg_curl_easy_setopt_haproxyprotocol) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPROXYPROTOCOL); }
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
                                                                                          CURLOPT_DEFAULT_PROTOCOL
pg_curl.c: In function âpg_curl_easy_setopt_http09_allowedâ:
pg_curl.c:423:89: error: âCURLOPT_HTTP09_ALLOWEDâ undeclared (first use in this function); did you mean âCURLOPT_HTTP200ALIASESâ?
 EXTENSION(pg_curl_easy_setopt_http09_allowed) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HTTP09_ALLOWED); }
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~
                                                                                         CURLOPT_HTTP200ALIASES
pg_curl.c: In function âpg_curl_easy_setopt_upkeep_interval_msâ:
pg_curl.c:496:93: error: âCURLOPT_UPKEEP_INTERVAL_MSâ undeclared (first use in this function); did you mean âCURLOPT_TCP_KEEPINTVLâ?
 EXTENSION(pg_curl_easy_setopt_upkeep_interval_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPKEEP_INTERVAL_MS); }
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                             CURLOPT_TCP_KEEPINTVL
pg_curl.c: In function âpg_curl_easy_setopt_upload_buffersizeâ:
pg_curl.c:497:92: error: âCURLOPT_UPLOAD_BUFFERSIZEâ undeclared (first use in this function); did you mean âCURLOPT_BUFFERSIZEâ?
 EXTENSION(pg_curl_easy_setopt_upload_buffersize) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPLOAD_BUFFERSIZE); }
                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                            CURLOPT_BUFFERSIZE
pg_curl.c: In function âpg_curl_easy_setopt_doh_urlâ:
pg_curl.c:315:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_doh_url) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_DOH_URL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_proxy_tls13_ciphersâ:
pg_curl.c:344:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_proxy_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_PROXY_TLS13_CIPHERS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_tls13_ciphersâ:
pg_curl.c:369:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_TLS13_CIPHERS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_disallow_username_in_urlâ:
pg_curl.c:401:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_disallow_username_in_url) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DISALLOW_USERNAME_IN_URL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_dns_shuffle_addressesâ:
pg_curl.c:403:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_dns_shuffle_addresses) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DNS_SHUFFLE_ADDRESSES); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_happy_eyeballs_timeout_msâ:
pg_curl.c:420:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_happy_eyeballs_timeout_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_haproxyprotocolâ:
pg_curl.c:421:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_haproxyprotocol) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPROXYPROTOCOL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_http09_allowedâ:
pg_curl.c:423:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_http09_allowed) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HTTP09_ALLOWED); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_upkeep_interval_msâ:
pg_curl.c:496:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_upkeep_interval_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPKEEP_INTERVAL_MS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_upload_buffersizeâ:
pg_curl.c:497:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_upload_buffersize) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPLOAD_BUFFERSIZE); }
 ^~~~~~~~~
<builtin>: recipe for target 'pg_curl.o' failed
make: *** [pg_curl.o] Error 1

> 

=========================================

> 

root@user:/tmp/pg_curl# make install
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o pg_curl.o pg_curl.c
pg_curl.c: In function âpg_curl_easy_setopt_doh_urlâ:
pg_curl.c:315:82: error: âCURLOPT_DOH_URLâ undeclared (first use in this function); did you mean âCURLOPT_URLâ?
 EXTENSION(pg_curl_easy_setopt_doh_url) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_DOH_URL); }
                                                                                  ^~~~~~~~~~~~~~~
                                                                                  CURLOPT_URL
pg_curl.c:315:82: note: each undeclared identifier is reported only once for each function it appears in
pg_curl.c: In function âpg_curl_easy_setopt_proxy_tls13_ciphersâ:
pg_curl.c:344:94: error: âCURLOPT_PROXY_TLS13_CIPHERSâ undeclared (first use in this function); did you mean âCURLOPT_PROXY_SSL_CIPHER_LISTâ?
 EXTENSION(pg_curl_easy_setopt_proxy_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_PROXY_TLS13_CIPHERS); }
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                              CURLOPT_PROXY_SSL_CIPHER_LIST
pg_curl.c: In function âpg_curl_easy_setopt_tls13_ciphersâ:
pg_curl.c:369:88: error: âCURLOPT_TLS13_CIPHERSâ undeclared (first use in this function); did you mean âCURLOPT_DNS_SERVERSâ?
 EXTENSION(pg_curl_easy_setopt_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_TLS13_CIPHERS); }
                                                                                        ^~~~~~~~~~~~~~~~~~~~~
                                                                                        CURLOPT_DNS_SERVERS
pg_curl.c: In function âpg_curl_easy_setopt_disallow_username_in_urlâ:
pg_curl.c:401:99: error: âCURLOPT_DISALLOW_USERNAME_IN_URLâ undeclared (first use in this function); did you mean âCURLOPT_TLSAUTH_USERNAMEâ?
 EXTENSION(pg_curl_easy_setopt_disallow_username_in_url) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DISALLOW_USERNAME_IN_URL); }
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                   CURLOPT_TLSAUTH_USERNAME
pg_curl.c: In function âpg_curl_easy_setopt_dns_shuffle_addressesâ:
pg_curl.c:403:96: error: âCURLOPT_DNS_SHUFFLE_ADDRESSESâ undeclared (first use in this function); did you mean âCURLOPT_DNS_SERVERSâ?
 EXTENSION(pg_curl_easy_setopt_dns_shuffle_addresses) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DNS_SHUFFLE_ADDRESSES); }
                                                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                CURLOPT_DNS_SERVERS
pg_curl.c: In function âpg_curl_easy_setopt_happy_eyeballs_timeout_msâ:
pg_curl.c:420:100: error: âCURLOPT_HAPPY_EYEBALLS_TIMEOUT_MSâ undeclared (first use in this function); did you mean âCURLOPT_EXPECT_100_TIMEOUT_MSâ?
 EXTENSION(pg_curl_easy_setopt_happy_eyeballs_timeout_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS); }
                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                    CURLOPT_EXPECT_100_TIMEOUT_MS
pg_curl.c: In function âpg_curl_easy_setopt_haproxyprotocolâ:
pg_curl.c:421:90: error: âCURLOPT_HAPROXYPROTOCOLâ undeclared (first use in this function); did you mean âCURLOPT_DEFAULT_PROTOCOLâ?
 EXTENSION(pg_curl_easy_setopt_haproxyprotocol) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPROXYPROTOCOL); }
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~
                                                                                          CURLOPT_DEFAULT_PROTOCOL
pg_curl.c: In function âpg_curl_easy_setopt_http09_allowedâ:
pg_curl.c:423:89: error: âCURLOPT_HTTP09_ALLOWEDâ undeclared (first use in this function); did you mean âCURLOPT_HTTP200ALIASESâ?
 EXTENSION(pg_curl_easy_setopt_http09_allowed) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HTTP09_ALLOWED); }
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~
                                                                                         CURLOPT_HTTP200ALIASES
pg_curl.c: In function âpg_curl_easy_setopt_upkeep_interval_msâ:
pg_curl.c:496:93: error: âCURLOPT_UPKEEP_INTERVAL_MSâ undeclared (first use in this function); did you mean âCURLOPT_TCP_KEEPINTVLâ?
 EXTENSION(pg_curl_easy_setopt_upkeep_interval_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPKEEP_INTERVAL_MS); }
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                             CURLOPT_TCP_KEEPINTVL
pg_curl.c: In function âpg_curl_easy_setopt_upload_buffersizeâ:
pg_curl.c:497:92: error: âCURLOPT_UPLOAD_BUFFERSIZEâ undeclared (first use in this function); did you mean âCURLOPT_BUFFERSIZEâ?
 EXTENSION(pg_curl_easy_setopt_upload_buffersize) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPLOAD_BUFFERSIZE); }
                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                            CURLOPT_BUFFERSIZE
pg_curl.c: In function âpg_curl_easy_setopt_doh_urlâ:
pg_curl.c:315:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_doh_url) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_DOH_URL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_proxy_tls13_ciphersâ:
pg_curl.c:344:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_proxy_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_PROXY_TLS13_CIPHERS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_tls13_ciphersâ:
pg_curl.c:369:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_tls13_ciphers) { return pg_curl_easy_setopt_char(fcinfo, CURLOPT_TLS13_CIPHERS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_disallow_username_in_urlâ:
pg_curl.c:401:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_disallow_username_in_url) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DISALLOW_USERNAME_IN_URL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_dns_shuffle_addressesâ:
pg_curl.c:403:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_dns_shuffle_addresses) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_DNS_SHUFFLE_ADDRESSES); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_happy_eyeballs_timeout_msâ:
pg_curl.c:420:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_happy_eyeballs_timeout_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_haproxyprotocolâ:
pg_curl.c:421:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_haproxyprotocol) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HAPROXYPROTOCOL); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_http09_allowedâ:
pg_curl.c:423:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_http09_allowed) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_HTTP09_ALLOWED); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_upkeep_interval_msâ:
pg_curl.c:496:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_upkeep_interval_ms) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPKEEP_INTERVAL_MS); }
 ^~~~~~~~~
pg_curl.c: In function âpg_curl_easy_setopt_upload_buffersizeâ:
pg_curl.c:497:1: warning: control reaches end of non-void function [-Wreturn-type]
 EXTENSION(pg_curl_easy_setopt_upload_buffersize) { return pg_curl_easy_setopt_long(fcinfo, CURLOPT_UPLOAD_BUFFERSIZE); }
 ^~~~~~~~~
<builtin>: recipe for target 'pg_curl.o' failed
make: *** [pg_curl.o] Error 1

>

**Comment by RekGRpth** [comment]
what is your curl version?
I use https://pkgs.alpinelinux.org/package/v3.13/main/x86_64/curl-dev
