### ISSUE TITLE
email ssl

### ISSUE THREAD

**Issue by hardex** [RekGRpth/pg_curl#4]
Hello,

I tried to change the procedure to send email using ssl and HTTP 2.0 request type.

CREATE OR REPLACE FUNCTION email_ssl(url TEXT, username TEXT, password TEXT, subject TEXT, "from" TEXT, "to" TEXT, data TEXT, type TEXT) RETURNS TEXT LANGUAGE SQL AS $BODY$
    WITH s AS (SELECT
        curl_easy_reset(),
        curl_easy_setopt_http_version(3), -- CURL_HTTP_VERSION_2_0
        curl_easy_setopt_url(url),
        curl_easy_setopt_use_ssl(3), -- CURLUSESSL_ALL
        curl_easy_setopt_username(username),
        curl_easy_setopt_password(password),
        curl_recipient_append("to"),
        curl_header_append('Subject', subject),
        curl_header_append('From', "from"),
        curl_header_append('To', "to"),
        curl_mime_data(data, type:=type),
        curl_easy_perform(),
        curl_easy_getinfo_headers()
    ) SELECT curl_easy_getinfo_headers FROM s;
$BODY$; 

Run :
select public.email_ssl('https://smtp.gmail.com:465', 'xx@yyyyyyy.com', '<pass>', 'test', 'xx@yyyyyyy.com', 'yy@xxxxxxx.com', 'Hello, test letter', 'text');

I got an error :
SQL Error [XX000]: ERROR: pg_curl_easy_perform(pg_curl.c:543): curl_easy_perform: Unsupported protocol: Received HTTP/0.9 when not allowed
  Where: SQL function "email_ssl" statement 1

I found that curl should be compiled with nghttp2 for supporting http2.0, but I do not know where to check this.
My pg_config :

pg_config
BINDIR = /Library/PostgreSQL/13/bin
DOCDIR = /Library/PostgreSQL/13/doc/postgresql
HTMLDIR = /Library/PostgreSQL/13/doc/postgresql
INCLUDEDIR = /Library/PostgreSQL/13/include
PKGINCLUDEDIR = /Library/PostgreSQL/13/include/postgresql
INCLUDEDIR-SERVER = /Library/PostgreSQL/13/include/postgresql/server
LIBDIR = /Library/PostgreSQL/13/lib
PKGLIBDIR = /Library/PostgreSQL/13/lib/postgresql
LOCALEDIR = /Library/PostgreSQL/13/share/locale
MANDIR = /Library/PostgreSQL/13/share/man
SHAREDIR = /Library/PostgreSQL/13/share/postgresql
SYSCONFDIR = /Library/PostgreSQL/13/etc/postgresql
PGXS = /Library/PostgreSQL/13/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--with-llvm' '--with-icu' '--enable-debug' '--host=x86_64-apple-darwin' '--prefix=/opt/pginstaller_13.auto/server/staging_cache/osx.build' '--with-ldap' '--with-openssl' '--with-perl' '--with-python' '--with-tcl' '--with-bonjour' '--with-pam' '--enable-thread-safety' '--with-libxml' '--with-uuid=e2fs' '--with-includes=/opt/local/Current/include/libxml2:/opt/local/Current/include:/opt/local/Current/include/security:/opt/local/libexec/llvm-8.0/include:/opt/local/Current/include/openssl/' '--docdir=/opt/pginstaller_13.auto/server/staging_cache/osx.build/doc/postgresql' '--with-libxslt' '--with-libedit-preferred' '--with-gssapi' 'host_alias=x86_64-apple-darwin' 'CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -arch x86_64 -O2' 'LDFLAGS=-L/opt/local/Current/lib -L/opt/local/libexec/llvm-8.0/lib' 'LLVM_CONFIG=/opt/local/bin/llvm-config-mp-8.0' 'CLANG=/opt/local/bin/clang-mp-8.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk' 'ICU_CFLAGS=-I/opt/local/Current/include' 'ICU_LIBS=-L/opt/local/Current/lib -licuuc -licudata -licui18n' 'XML2_CONFIG=/opt/local/Current/bin/xml2-config' 'PERL=/Library/edb/languagepack/v1/Perl-5.26/bin/perl' 'PYTHON=/Library/edb/languagepack/v1/Python-3.7/bin/python3'
CC = gcc
CPPFLAGS = -I/opt/local/Current/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/opt/local/20200428/include/libxml2 -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -I/opt/local/libexec/llvm-8.0/include -I/opt/local/Current/include/openssl/
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -g -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -arch x86_64 -O2
CFLAGS_SL = 
LDFLAGS = -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -L/opt/local/Current/lib -L/opt/local/libexec/llvm-8.0/lib -L/opt/local/libexec/llvm-8.0/lib -L/opt/local/20200428/lib -Wl,-dead_strip_dylibs
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lm 
VERSION = PostgreSQL 13.4

Can you help to setup http 2.0 connection?

**Comment by RekGRpth** [comment]
firstly, try command line curl to test if it works

**Comment by RekGRpth** [comment]
pg_curl is only postgres implementation of command line curl

**Comment by hardex** [comment]
I successfully use these curl packages on postgres, it is working.
More of this, I added some procs :

CREATE OR REPLACE FUNCTION public.post(url text, userpwd text, request json)
 RETURNS text
 LANGUAGE sql
AS $function$
    WITH s AS (SELECT
        curl_easy_reset(),
        curl_easy_setopt_url(url),
        curl_easy_setopt_userpwd(userpwd),
        curl_header_append('Content-Type', 'application/json; charset=utf-8'),
        curl_easy_setopt_copypostfields(convert_to(request::TEXT, 'utf-8')),
        curl_easy_perform(),
        curl_easy_getinfo_response()
    ) SELECT convert_from(curl_easy_getinfo_response, 'utf-8') FROM s;
$function$
;

CREATE OR REPLACE FUNCTION public.delete(url text, userpwd text)
 RETURNS text
 LANGUAGE sql
AS $function$
    WITH s AS (SELECT
        curl_easy_reset(),
        curl_easy_setopt_customrequest('DELETE'),
        curl_easy_setopt_url(url),
        curl_easy_setopt_userpwd(userpwd),
        curl_easy_perform(),
        curl_easy_getinfo_response(),
        curl_easy_getinfo_response_code(url)
    ) SELECT curl_easy_getinfo_response_code::text FROM s;
$function$
;

CREATE OR REPLACE FUNCTION public.put(url text, userpwd text, request json)
 RETURNS text
 LANGUAGE sql
AS $function$
    WITH s AS (SELECT
        curl_easy_reset(),
        curl_easy_setopt_customrequest('PUT'),
        curl_easy_setopt_url(url),
        curl_easy_setopt_userpwd(userpwd),
        curl_header_append('Content-Type', 'application/json; charset=utf-8'),
        curl_easy_setopt_copypostfields(convert_to(request::TEXT, 'utf-8')),
        curl_easy_perform(),
        curl_easy_getinfo_response()
    ) SELECT convert_from(curl_easy_getinfo_response, 'utf-8') FROM s;
$function$
;

**Comment by RekGRpth** [comment]
also, there is more simple way to use pg_curl
```sql
create or replace function email(...) returns text language plpgsql as $body$ <<local>> declare
    url text;
    recipient text;
    subject text;
    sender text;
    body text;
begin
    perform curl_easy_reset();
    --perform curl_easy_setopt_verbose(1);
    perform curl_easy_setopt_url(url);
    perform curl_recipient_append(recipient);
    perform curl_header_append('To', recipient);
    perform curl_header_append('Subject', subject);
    perform curl_header_append('From', sender);
    --perform curl_easy_setopt_mail_from(sender);
    perform curl_mime_data(body, type:='text/plain; charset=utf-8', code:='base64');
    perform curl_easy_setopt_timeout(10);
    perform curl_easy_perform(5);
    return curl_easy_getinfo_headers();
end;$body$;
```

**Comment by RekGRpth** [comment]
hm...
```sh
curl "https://smtp.gmail.com:465"
curl: (1) Received HTTP/0.9 when not allowed
```
but
```sh
curl --http0.9 "https://smtp.gmail.com:465"
220 smtp.gmail.com ESMTP u17sm332854lfm.279 - gsmtp
502 5.5.1 Unrecognized command. u17sm332854lfm.279 - gsmtp
```

**Comment by RekGRpth** [comment]
working example with gmail
```sql
select curl_easy_reset();
select curl_easy_setopt_mail_from('username@gmail.com');
select curl_easy_setopt_password('password');
select curl_easy_setopt_timeout(10);
select curl_easy_setopt_url('smtp://smtp.gmail.com:587');
select curl_easy_setopt_username('username@gmail.com');
select curl_easy_setopt_use_ssl(3);
select curl_easy_setopt_verbose(1);
select curl_header_append('From', 'username@gmail.com');
select curl_header_append('Subject', 'Subject');
select curl_header_append('To', 'recipient@gmail.com');
select curl_mime_data('Body', type:='text/plain; charset=utf-8');
select curl_recipient_append('recipient@gmail.com');
select curl_easy_perform(5);
select curl_easy_getinfo_headers();
```

**Comment by RekGRpth** [comment]
> I successfully use these curl packages on postgres, it is working.

hope you use pg_curl with pg_task? ;)

**Comment by hardex** [comment]
For me this is working with gmail too, but don't working with ukr.net.
And I do not have any logs to send them. But ukr.net is for personal use and do not in priority.
In gmail there are ports : 
- for SSL: 465
- for TLS/STARTTLS: 587
and with 587 it is working.
But in ukr.net instruction only ssl and I don't have enough knowledges to understand the difference.

Thank you for prompt response!

**Comment by RekGRpth** [comment]
> I do not have any logs

```sql
select curl_easy_setopt_verbose(1);
```
and log appears in postgres log
