### ISSUE TITLE
Wrong stuff bytes at start of data

### ISSUE THREAD

**Issue by ukolovda** [RekGRpth/pg_curl#6]
With some sites pg_curl give wrong result.

For example: 
```sql
WITH s AS (SELECT
             curl_easy_reset(),
             curl_easy_setopt_url('https://www.tarifer.ru'),
             curl_easy_perform(),
             curl_easy_getinfo_data_in()
) SELECT convert_from(curl_easy_getinfo_data_in, 'utf-8') FROM s;
```
I'v got `[22021] ERROR: invalid byte sequence for encoding "UTF8": 0xd0 0x0d`

Binary data:
```sql
WITH s AS (SELECT
             curl_easy_reset(),
             curl_easy_setopt_url('https://www.tarifer.ru'),
             curl_easy_perform(),
             curl_easy_getinfo_data_in()
) SELECT curl_easy_getinfo_data_in FROM s;
```
have `0x316366340D0A` extra symbols at start.

I try latest PostgreSQL 14.1 (docker version) and latest pg_curl.

**Comment by ukolovda** [comment]
I try previous version `69f38eac` (at `Jan 22, 2021`), it works correct.

```sql
WITH s AS (SELECT
             curl_easy_reset(),
             curl_easy_setopt_url('https://www.tarifer.ru'),
             curl_easy_perform(),
             curl_easy_getinfo_response()
) SELECT curl_easy_getinfo_response FROM s;
```

**Comment by RekGRpth** [comment]
> With some sites pg_curl give wrong result.

it is because Transfer-Encoding:  chunked
temp solution
```sql
select curl_easy_setopt_http_version(curl_http_version_1_0());
```
> have `0x316366340D0A` extra symbols at start.

extra symbols added not only at start

**Comment by RekGRpth** [comment]
fixed by https://github.com/RekGRpth/pg_curl/commit/44dcced5f4eed170f7b9ae041b5f9c622615a19b thank You for issue!

**Comment by ukolovda** [comment]
Thank you!
This error occured also when I get data from ClickHouse database.
I will check new version.
