### ISSUE TITLE
Github releases vs pgxn

### ISSUE THREAD

**Issue by devrimgunduz** [RekGRpth/pg_curl#9]
Hi,

pg_curl shows 2.0.2 on pgxn, and "master" on github. I assume pgxn is correct, as "master" is not a release. Is that correct?

I will RPMify this package, that is why I am asking.

Thanks!

Devrim

**Comment by RekGRpth** [comment]
I don't quite understand what this means?

> pg_curl shows 2.0.2 on pgxn, and "master" on github

**Comment by devrimgunduz** [comment]
On PGXN, release version is 2.0.2.

On github, there is not an actual release: https://github.com/RekGRpth/pg_curl/releases <-- "master.tar.gz"

Is this expected?

**Comment by RekGRpth** [comment]
> Is this expected?

Yes, I just do not put tags in the github.

**Comment by devrimgunduz** [comment]
Ack, thanks.

**Comment by RekGRpth** [comment]
> On github, there is not an actual release: https://github.com/RekGRpth/pg_curl/releases <-- "master.tar.gz"

No, this is absolutely the same as in pgxn.

**Comment by RekGRpth** [comment]
Moreover, it is this archive that is automatically uploaded to pgxn ;)
